NAME        = unnecessary_violence

CXX         = c++
CXXFLAGS    = -Wall -Wextra -Werror -std=c++98 -pedantic


SRCS        = main.cpp \
              Weapon.cpp \
              HumanA.cpp \
              HumanB.cpp

OBJS        = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp Weapon.hpp HumanA.hpp HumanB.hpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
