NAME        = idontwanttosettheworldonfire
CXX         = c++
CXXFLAGS    = -Wall -Wextra -Werror -g -std=c++98 -pedantic

SRCS        = main.cpp Animal.cpp Dog.cpp Cat.cpp Brain.cpp
OBJS        = $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
